export const ROUTES = {
	AUTH: {
		ROOT: "/auth",
		LOGIN: "login",
	},
	ADMIN: {
		ROOT: "/admin",
		DASHBOARD: "dashboard",
		PROFILE: "profile",
		CHANGE_PASSWORD: "change-password",
		USERS: "users",
		SETTING: "setting",
	},
};

export const FULL_ROUTES = {
	//auth
	AUTH_LOGIN: `${ROUTES.AUTH.ROOT}/${ROUTES.AUTH.LOGIN}`,
	ADMIN_PROFILE: `${ROUTES.ADMIN.ROOT}/${ROUTES.ADMIN.PROFILE}`,
	ADMIN_CHANGE_PASSWORD: `${ROUTES.ADMIN.ROOT}/${ROUTES.ADMIN.CHANGE_PASSWORD}`,

	//admin
	ADMIN_DASHBOARD: `${ROUTES.ADMIN.ROOT}/${ROUTES.ADMIN.DASHBOARD}`,
	ADMIN_USER_LIST: `${ROUTES.ADMIN.ROOT}/${ROUTES.ADMIN.USERS}`,
	ADMIN_SETTING: `${ROUTES.ADMIN.ROOT}/${ROUTES.ADMIN.SETTING}`,
};
